import pandas
import matplotlib.pyplot as plt
df = pandas.read_csv('a8_d_Bebida.csv', header=0, names=['Time', 'Bebida'])
#print(df['Bebida'])
plt.subplots_adjust(bottom=0.5)
plt.subplot(2, 2, 1)
plt.scatter(df['Time'][:10], df['Bebida'][:10], 1000, alpha=0.5, marker=r'$\star$')
plt.grid(True)
plt.xticks(rotation='vertical')
plt.title('Bebidas elaboradas nos 10 primeiros dias')
plt.xlabel("Dia")
plt.ylabel("Bebidas")
plt.subplot(2, 2, 2)
plt.plot(df['Time'][-10:], df['Bebida'][-10:], color='green')
plt.grid(True)
plt.xticks(rotation='vertical')
plt.title('Bebidas elaboradas nos 10 ultimos dias')
plt.xlabel("Dia")
plt.ylabel("Bebidas")
plt.subplot(2, 2, 3)
plt.boxplot(df['Bebida'])
plt.grid(True)
plt.xticks(rotation='vertical')
plt.title('Boxplot das bebidas')
plt.xlabel("Dia")
plt.ylabel("Bebidas")
plt.subplot(2, 2, 4)
plt.plot(df['Time'][:30], df['Bebida'][:30])
plt.grid(True)
plt.xticks(rotation='vertical')
plt.title('Bebidas elaboradas nos 30 primeiros dias')
plt.xlabel("Dia")
plt.ylabel("Bebidas")
plt.tight_layout()
plt.savefig('ab2_introd.jpg', dpi = 3000)
